### PR TITLE
Make links open in a new tab

### PR DESCRIPTION
**Pull request by landml**
@jayrbolton, @bio-boris, @JamesJeffryes - As requested by the users at the SFA SDK training, the links in the documentation should all open in a new tab so users don't lose their place in the tutorial.

### CODE REVIEW

**Comment by jayrbolton** [comment]
I would vote for keeping internal links default behavior and only using target="_blank" on external links. From what I've seen, it's considered poor UX practice to use target="_blank" in general, although i think it makes sense for external links ([example google search](https://www.google.com/search?q=ux+target+blank+links&oq=ux+target+blank+links&aqs=chrome..69i57.3207j0j4&client=ubuntu&sourceid=chrome&ie=UTF-8)). 

Maybe part of the underlying issue is that the only place the SDK docs are linked is from the [sdk repo](https://github.com/kbase/kb_sdk). Maybe there are more places it can be linked from? I'll try to add the link to some other locations

**Comment by jayrbolton** [comment]
(but of course I'm totally willing to be vetoed on the above point^)

**Comment by landml** [comment]
The creator of reStructuredText is in full agreement with you Boris. His opinion is that the way it is now, everyone has the option of opening in a tab. With the requested change, everyone is forced to open in a tab. Personally, I have developed the same habit of explicitly opening in a new tab. However, it was a SFA SDK developer that went off on a rant about this issue. Should I put in a formal ticket or raise the issue on Slack?

**Comment by bio-boris** [comment]
@landml I think that's a good idea. I can also bring it up in standup if you'd like.

**Comment by landml** [comment]
@bio-boris - Raising the issue on the standup is probably a good idea. I made a ticket PUBLIC-557. That way, if the change is rejected, the justification can be documented for the developers to see. I should probably post this on the SFA developer Slack channel. Perhaps I was hearing a minority.

**Comment by elishawc** [comment]
I would prefer that external links open in a new tab. From a user retention perspective, if we link people away from our "branding", it is often difficult to get them back. (esp as mentioned above, the documentation is currently not easily discoverable)

I am negotiable on internal links.

**Comment by landml** [comment]
It seems like the compromise that works for the people who responded on Slack and here is to use a new tab for external sites only. Anything that stays on the documentation site will open in the same tab because it has the navigation sidebar. I can get that done today. 

Since today's changes will likely conflict with this PR, would it work to merge in this PR and later merge in today's changes?

**Comment by jayrbolton** [comment]
@landml Sounds good. I can merge this one and then we can do any follow ups

**Pull request merged**
