### PR TITLE
Documentation for new features

### PR DESCRIPTION
**Pull request by JamesJeffryes**
Let me know if I can elaborate anywhere. Should probably wait to merge till we approve the new Python3 SDK image

### CODE REVIEW

**Comment by jayrbolton** [comment]
I made some small copy edits, hope you don't mind.
whypy3.com is fun

**Comment by jayrbolton** [comment]
I compiled and validated all the rst locally, and also looked through things on the dev serve, and all looked good enough to me. So this is ready to go whenever the python 3 updates are deployed

**Comment by jayrbolton** [comment]
@JamesJeffryes Just out of curiosity, what was the status of the py3 support for the sdk? I wasn't sure what else it was waiting on

**Comment by jayrbolton** [comment]
This is going to have conflicts with Miriam's updates, particularly the UI specifications documentation update. I'm going to go ahead and merge this with master but hide the link to the py3 howto page and comment out the bit in the faq. That way I can resolve conflicts in Miriam's branch against these changes.

**Comment by JamesJeffryes** [comment]
It languished a bit because I have no way of forcing folks to try out the
beta or to make their modules in Python 3. I need to get that error message
change pushed it but Gavin wants tests and I haven't had the time to dig
into that mess

**Pull request merged**
