### PR TITLE
Make updates to SDK tutorial - SCT-769

### PR DESCRIPTION
**Pull request by landml**
@bio-boris, @jayrbolton , @JamesJeffryes 
Most of the changes I made were in the tutorial to improve the flow. Most of the other pages I found were great additions to the old version of the pages and only needed a light touch.

List of changes that I make to the SDK tutorial documentation.

- Fixed  typos and cleaned up a few things
- Sometimes the module is called an app and sometimes the method is called an app. I changed the wording to be consistent with the Module Catalog as being modules and what’s in the App Catalog is called an app, even though it is in the method directory.
- The “kb-sdk init” can be with or without the “—example”. The tutorial instructed the users to use the “—example” but the rest of the tutorial assumed that the user hadn’t done the “—example”.
-  reworded it back to the way the SDK classes run, with the “—example” . - Then I added a new page for the “naked” version and call it HelloWorld (an introduction to where the various files live) which comes first.
- Added a terminology page
- Focused the setup.rst on just the module.spec file because it was getting long and I created a separate page for doing the narrative interface ( spec.json and display.yaml ). I think that also highlights how they serve a different purpose than the module.spec file.
- Changed the link that was going to https://docs.google.com/document/d/1CZ1GOKsRr1NsScG9E2EesJyk_ViOrM9OazrVFKCkyHs (where there are edits and comments) and pointed it the UI_spec page.

### CODE REVIEW

**Comment by jayrbolton** [comment]
Thanks @landml , I will review and test this

**Comment by jayrbolton** [comment]
I had a large amount of copy changes on the `UI_spec.rst` document in another PR that I will merge into here, trying to make sure that the changes here are not overwritten.

**Comment by bio-boris** [comment]
@jayrbolton Not sure why there is a token in the initialize.html

**Comment by jayrbolton** [comment]
Ah shoot, that looks to have been added here. If it's an active token, it should get revoked as it's now all over the git history.
@landml is this an active developer token you are using? If so, can you revoke it in your account settings as soon as you can?
https://github.com/kbase/kb_sdk_docs/pull/14/files#diff-821f21eabd7017b5bd9e1b046fedfe33R122

**Comment by landml** [comment]
@jayrbolton - I used an artificial developer token.

**Pull request merged**
